- name: install and run nginx
  host: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.bultin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true


