- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: dream
    prompt: what is your Dream?
    private: false
  - name: code
    prompt: what is your lucky code?
    private: true
  tasks:
  - name: Assessment of Goal fulfillment
    ansible.builtin.debug:
      msg: " Hi, Your Dream {{dream }} is reacheable if your are confident enough and hardworking!!! "
  - name: Lucky code
    ansible.builtin.debug:
      msg: " Hi, Your lucky code : {{ code }}  "
      
