- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your Dream?
    private: false
  tasks:
  - name: Assessment of Goal fulfillment
    ansible.builtin.debug:
      msg: " Hi, Your Dream {{username}} is reacheable if your are confident enough and hardworking!!! "
      
