- name: using modules based on ansible_facts or  gather facts
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx if OS is RedHat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install nginx if OS is Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: latest
    when: ansible_os_family == "Debian"



    # we can use this feature of understanding target server and make decisions and write our own code or modules based on server facts by gathering facts (ansible_facts) understand existing configuration of server