- name: package installing play
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install looped packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - nginx
    - zip
    - tree
    - mysql