- name: functions
  hosts: local
  connection: local
  vars:
    name: defining variable here  # eventhough name is a reserved keyword in ansible I am using it to practice
    technologies: Devops, linux, shell, ansible #string
    gmail: VIshWas@2025AUGUST.cOm
    IPaddress: 199.26.78.65
    #dictionary == map
    Tags:
      Application: payment
      Environment: dev
    ListTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev 
  tasks:
  - name: default variable
    ansible.builtin.debug:
#      msg: "Hello {{ name }}"   --> undefined variable
       msg: "Hello {{ name | default(' providing default Value for variable name if it is not defined')}}"

  # string to list
  - name: convert string to list
    ansible.builtin.debug:
      msg: "Technologies are : {{ technologies | split(',') }}"
  
  # map to list
  - name: convert map to list
    ansible.builtin.debug:
      msg: " Tags are : {{ Tags | dict2items }} "  # dict(dictionary or map ) 2 to items(list)

  # list to map or dict
  - name: convert list to map
    ansible.builtin.debug:
      msg: "ListTags are {{ ListTags | items2dict}}"

  # read yaml file in runtime and store it as a string into a variable
  - name: read an entire yam file and store it in a variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"                   # student.yaml --> filepath
  
  - name: convert yam to json
    ansible.builtin.debug:
      msg: "{{student_yaml|to_json}}"

  - name: copy output JSON to a file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{student_yaml|to_nice_json}}"

  - name: case to upper
    ansible.builtin.debug:
      msg: "TO upper: {{ name | upper }}"

  - name: case to lower
    ansible.builtin.debug:
      msg: "TO lower: {{ gmail | lower }}"

  - name: ip address check
    ansible.builtin.debug:
      msg: "IP exists: {{ IPaddress |  ipaddr }}"


