- name: create user
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check if user exists
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ output }}"

  - name: create user based on output return code 
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0


    ### error handling : we will take output to a file using register and ignore errors and take necessary steps based on output

    
